spring:
  profiles.active: prod
---
spring:
  profiles: default
  mvc:
    ignore-default-model-on-redirect: false
  view:
    prefix: /WEB-INF/views/
    suffix: .jsp
server:
  port: 8080
---
spring:
  profiles: prod
  mvc:
    ignore-default-model-on-redirect: false
  view:
    prefix: /WEB-INF/views/
    suffix: .jsp
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate.ddl-auto: create    
server:
  port: 8080