spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/recruit
    username: developer
    password: developer
  mvc:
    ignore-default-model-on-redirect: false
  view:
    prefix: /WEB-INF/views/
    suffix: .jsp
server:
  port: 8080
